import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

import localFont from 'next/font/local';

const myCustomFont = localFont({
  src: [
    {
      path: '../../public/fonts/font.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/font.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-my-custom', // Optional: for use with CSS variables
  display: 'swap', // Optional: for better font loading performance
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myCustomFont.className} bg-[#fdf6f0]`}>
      <body
        className="bg-[#fdf6f0]"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
